# General
title:          Amy R. Wong 王蕊
description:    Scholar, Literary Critic, Professor, Psychoanalyst-in-Training
url:            https://glennpoppe.github.io
baseurl:        "/amyrwong"

# Navigation
permalink:      /:slug

# Minify CSS
sass:
  style: compressed
  sourcemap: never

# Contact
author:
  name: Amy R. Wong 王蕊
  email: amyreiwong@gmail.com

# Gems
plugins:
#  - jekyll-feed
  - jekyll-sitemap

highlighter: rouge

exclude:
  - new_post.sh
